name: 'Apply labels on a new issue'
on:
  issues:
    types: [opened]

permissions: read-all

jobs:
  apply-labels-on-issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'grafana' }}
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          persist-credentials: false
    
      - name: Run apply-component-labels.sh
        run: ./.github/workflows/scripts/apply-component-labels.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.number }}
          BODY: ${{ github.event.issue.body }}
