name: Check Windows build image

on:
  pull_request:
    paths:
      - 'tools/build-image/windows/**'

permissions:
  contents: read

jobs:
  check-windows-build-image:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          persist-credentials: false

      - name: Create test Windows build image
        uses: mr-smithers-excellent/docker-build-push@05b44e1dd9e03f78e8689bd1a61c750f17907ffe # v6.11
        with:
          image: grafana/alloy-build-image
          tags: latest
          registry: docker.io
          pushImage: false
          dockerfile: ./tools/build-image/windows/Dockerfile
