name: Snyk Monitor Scanning
on:
  release:
    types: [published]
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snyk-scan-ci:
    uses: grafana/security-github-actions/.github/workflows/snyk_monitor.yml@7398d7d15e6357bdcdab41d9a3e52b6bf314d0e5 # main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
