name: Test Linux system packages
on:
  push:
    branches:
      - main
    paths:
    - packaging/**
    - internal/tools/packaging_test/**
    - Makefile
    - tools/make/*.mk

permissions:
  contents: read

jobs:
  test_linux_system_packages:
    name: Test Linux system packages
    runs-on: ubuntu-latest
    container:
      image: grafana/alloy-build-image:v0.1.35@sha256:9fa2a341b53503ce42cf9900c401d689a68ea67cdec6a20f53d72e3665fb8dc6
      volumes:
        - /var/run/docker.sock
    steps:
    - name: Checkout code
      uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      with:
        persist-credentials: false
    - name: Set ownership
      # https://github.com/actions/runner/issues/2033#issuecomment-1204205989
      run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
    - name: Set up Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
      with:
        go-version-file: go.mod
        # TODO: Enable caching later
        cache: false
    - run: DOCKER_OPTS="" make dist/alloy-linux-amd64
    - run: DOCKER_OPTS="" make test-packages
